`ifndef TEST_CONSTANTS_V
`define TEST_CONSTANTS_V

`define ADDR_SWITCH 6'd0
`define ADDR_ESII 6'd1
`define ADDR_INST_MODEL 6'd2
`define ADDR_INST_ID 6'd3
`define ADDR_TIMESTAMP 6'd4
`define ADDR_FLASH_RDATA 6'd5
`define ADDR_VERSION 6'd6
`define ADDR_ESPMCOMM_CRCGOOD 6'd7
`define ADDR_ESPMCOMM_CRCERR 6'd8
`define ADDR_PRELOAD 6'd9
`define OFF_POT_DATA 3'd0
`define ESPM_FIRMWARE_VERSION 32'h0000_0001

`endif // TEST_CONSTANTS_V
